project:
  type: website
  output-dir: docs

website:
  title: "Data Catalog"
  navbar:
    right:
      - updates.qmd
      - about.qmd
  search: false

format:
  html:
    theme: flatly
    css: styles.css



