project:
  type: website

website:
  title: "Data Catalog"
  favicon: assets/logo.png
  navbar:
    right:
      - updates/index.qmd
      - about.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/CEHI-code-repos/GISDataCatalog
          - text: Report an Issue
            href: https://github.com/CEHI-code-repos/GISDataCatalog/issues

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true

