project:
  type: website

website:
  title: "Data Catalog"
  navbar:
    right:
      - text: Favorites
        href: five_favorites.qmd
      - updates.qmd
      - about.qmd
  search: false

format:
  html:
    theme: flatly



