---
title: "Data Catalog"
date-modified: last-modified
format: 
    html:
        toc: true
    PrettyPDF-pdf:
        toc: true
        colorlinks: true
---

{{< pagebreak >}}

## 500 Cities

+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**         | The [500 Cities Project](https://www.cdc.gov/places/about/500-cities-2016-2019/index.html) provided model derived estimates for chronic disease risk factors, health outcomes, and clinical preventive services use for the 500 largest US cities.                                                                                                                                  |
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Time Frame**          | Year; 2016 to 2019                                                                                                                                                                                                                                                                                                                                                                  |
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Spatial Scale**       | City and Census Tract                                                                                                                                                                                                                                                                                                                                                               |
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Format**              | Tables and Shapefiles                                                                                                                                                                                                                                                                                                                                                               |
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Source**              | Centers for Disease Control and Prevention (CDC)                                                                                                                                                                                                                                                                                                                                    |
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Original Repository** | [All Years](https://data.cdc.gov/browse?q=GIS%20friendly&sortBy=relevance) (Look for datasets labeled GIS Friendly Format)                                                                                                                                                                                                                                                          |
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Living Atlas**        | [2016](https://cdcarcgis.maps.arcgis.com/home/item.html?id=ea8b721cf9034814bce067ddefd21ecc) [2017](https://cdcarcgis.maps.arcgis.com/home/item.html?id=2064702cb1fe47e5868333f56d4c99d0) [2018](https://cdcarcgis.maps.arcgis.com/home/item.html?id=04bd589e13c242d98de43e78f90d0d3f) [2019](https://cdcarcgis.maps.arcgis.com/home/item.html?id=7f48652a35424b97b2bc2542c4ef26ae) |
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[20,80\]"}

**Details**\
This project reported city- and census tract-level data and used small area estimation methods to obtain 27 chronic disease measures for the 500 largest American cities. Dataset includes estimates for 27 measures ([definitions here](https://www.cdc.gov/places/measure-definitions/index.html)):

-   Chronic disease-related unhealthy behaviors (5),
-   Health outcomes (13), and
-   Use of preventive services (9).

These estimates can be used to identify emerging health problems and to inform development and implementation of effective, targeted public health prevention activities. Because the small area model cannot detect effects due to local interventions, users are cautioned against using these estimates for program or policy evaluations.

{{< pagebreak >}}

## American Community Survey (ACS) 5-year Estimates

+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**         | "The [American Community Survey](https://www.census.gov/programs-surveys/acs/about.html) (ACS) is an ongoing survey that provides vital information on a yearly basis about our nation and its people. Information from the survey generates data that help determine how more than \$675 billion in federal and state funds are distributed each year.” (U.S Census Bureau) |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Time Frame**          | 5 Years; 2009 to 2022                                                                                                                                                                                                                                                                                                                                                        |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Spatial Scale**       | Nation, States (including DC and Puerto Rico), Metropolitan Areas, Congressional Districts, Counties, Places, Census Tracts and Block Groups                                                                                                                                                                                                                                 |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Format**              | Feature Layers                                                                                                                                                                                                                                                                                                                                                               |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Source**              | US Census Bureau                                                                                                                                                                                                                                                                                                                                                             |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Original Repository** | [All Years](https://data.census.gov/)                                                                                                                                                                                                                                                                                                                                        |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Living Atlas**        | [Current](https://www.arcgis.com/home/group.html?id=16b3a5ac36834ed6b3f16261d9a988ea#overview)                                                                                                                                                                                                                                                                               |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[20,80\]"}

**Details**\
The Living Atlas hosts the current ACS 5-year estimates in a series of several features grouped by topic. Each topic is hosted as both [boundaries and centroids](https://storymaps.arcgis.com/stories/41743d0d5364488fb51d795d65b40b37). Topics may contain single or multiple ACS tables Layers can be [accessed and used](https://www.arcgis.com/apps/Cascade/index.html?appid=c6a35a434a8f4913b9c35022290efdd0) within your GIS workflows, for example, [make a map about your community](https://www.esri.com/arcgis-blog/products/arcgis-living-atlas/mapping/make-an-acs-map-fast/).

If you are looking for historical data, the census.gov website can be difficult to go through. [Census Reporter](https://censusreporter.org/) can make it easier to find and download tables at various spatial scales.

{{< pagebreak >}}

## Climate & Economic Justice Screening Tool (CEJST)

+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**         | Identifies communities that experience disadvantages due to a combination of environmental and socioeconomic factors. It assists federal agencies in distributing money to improve climate and economic fairness. |
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Time Frame**          | Updated on Unknown Basis; Current                                                                                                                                                                                 |
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Spatial Scale**       | Census tract level across the United States, the District of Columbia, as well as the U.S. territories.                                                                                                           |
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Format**              | CSV and Shapefiles                                                                                                                                                                                                |
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Source**              | Council on Environmental Quality (CEQ)                                                                                                                                                                            |
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Original Repository** | [All Years](https://screeningtool.geoplatform.gov/en/methodology)                                                                                                                                                 |
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Living Atlas**        |                                                                                                                                                                                                                   |
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

{tbl-colwidths="\[20,80\]"}

**Details**\
The tool uses databases to detect climatic, environmental, and other stresses on communities. We may classify indicators according to topics like energy, housing, legacy pollution, transportation, and workforce development, among others. Specific factors include expected flood risk, energy cost burden, traffic proximity, and so forth. The data and techniques utilized are explained in the CEJST Technical Support Document, which is available for download. The tool supports the Biden-Harris Administration's commitment to combating unfairness and inequality by allocating resources to the most vulnerable communities.

{{< pagebreak >}}

## CMS Approved Facilities - FQHC, RHC, CAH

+-------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**         | This service provides information on Center of Medicare & Medicaid Services (CMS) approved facilities such as federally qualified health centers (FQHCs), rural health clinics, critical access hospitals and nursing facilities. |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Time Frame**          | Updated on Unknown Basis; Current                                                                                                                                                                                                 |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Spatial Scale**       | Point                                                                                                                                                                                                                             |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Format**              | Feature Service                                                                                                                                                                                                                   |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Source**              | Health Resources & Services Administration (HRSA)                                                                                                                                                                                 |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Original Repository** | [Current](https://gisportal.hrsa.gov/server/rest/services/HealthCareFacilities/CMSApprovedFacilities_FS/FeatureServer) ([Additional Information](https://data.hrsa.gov/maps/services))                                            |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Living Atlas**        | N/A                                                                                                                                                                                                                               |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[20,80\]"}

**Details**\
This is the “[Provider of Service](https://data.cms.gov/provider-characteristics/hospitals-and-other-facilities/provider-of-services-file-hospital-non-hospital-facilities/data)” extract from the Quality Improvement Evaluation System (QIES) database maintained by the Centers for Medicare & Medicaid Services (CMS). These data include provider number, name, and address and characterize the participating institutional provider (including hospitals, skilled nursing facilities, home health agencies, and other types of facilities).

Add to an ArcGIS Project by using “Data from Path” and paste the above URL as the server to use. Export using Feature Class to Feature Class.

{{< pagebreak >}}

## County Health Rankings & Roadmaps

+-------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**         | Provides information on health outcomes and health factors for all 50 states. It shows where improvements can be made and encourages fact-based answers. |
+-------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Time Frame**          | Year; 2010 to 2024                                                                                                                                       |
+-------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Spatial Scale**       | County levels across the United States                                                                                                                   |
+-------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Format**              | CSV and Shapefiles                                                                                                                                       |
+-------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Source**              | Robert Wood Johnson Foundation and the University of Wisconsin Population Health Initiative                                                              |
+-------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Original Repository** | [Current](https://www.countyhealthrankings.org/health-data)                                                                                              |
+-------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Living Atlas**        |                                                                                                                                                          |
+-------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+

|                             |
|-----------------------------|
| {tbl-colwidths="\[20,80\]"} |

**Details**\
This project gives information at the county level about different health results and things that affect health in the US. This dataset has values for a lot of different measures including:

-   Health Outcomes (e.g., length and quality of life)

-   Health Factors (e.g., health behaviors, clinical care, social and economic factors, and physical environment)

These estimates can help find places that need improvement and guide the creation and use of effective, focused health interventions. As a result of the difficulty in finding local intervention effects, users should be careful when using these figures to judge programs or policies.

{{< pagebreak >}}

## Division for Heart Disease and Stroke Prevention - Heart Disease and Stroke Mortality

+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**         | Heart Disease and Stoke Mortality                                                                                                                                                                                                                                                                                                                                              |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Time Frame**          | Three year average from 2005-2007 to 2019-2021                                                                                                                                                                                                                                                                                                                                 |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Spatial Scale**       | States, Counties                                                                                                                                                                                                                                                                                                                                                               |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Format**              | Tables                                                                                                                                                                                                                                                                                                                                                                         |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Source**              | Centers for Disease Control and Prevention (CDC) Division for Heart Disease and Stroke Prevention                                                                                                                                                                                                                                                                              |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Original Repository** | [Interactive Data Atlas](https://nccd.cdc.gov/DHDSPAtlas/Default.aspx)                                                                                                                                                                                                                                                                                                         |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Living Atlas**        | Heart Disease Mortality - [2014-2016](https://www.arcgis.com/home/item.html?id=d8b5477dad474e2d85cae6b8c069003e) [2017-2019](https://www.arcgis.com/home/item.html?id=ad21224485f049ee85808504c406c9ed) [2018-2020](https://www.arcgis.com/home/item.html?id=3d67302da1cf4b0d820b613c7949e958)                                                                                 |
|                         |                                                                                                                                                                                                                                                                                                                                                                                |
|                         | Stroke Mortality - [2014-2016](https://www.arcgis.com/home/item.html?id=21501f65faf84279afb41f040e82b4af) [2016-2018](https://www.arcgis.com/home/item.html?id=713d4cd763e24507b2b7688b96ab9416) [2017-2019](https://www.arcgis.com/home/item.html?id=417107aaaf7b471d918db5b2bafe9c9e) [2018-2020](https://www.arcgis.com/home/item.html?id=60a486432fcc4b70bcc5b9adf6155242) |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[20,80\]"}

**Details**\
Offers Heart Disease and Stroke mortality data obtained from the National Vital Statistics System. Data can be stratified by age, race/ethnicity, and gender. The Interactive Atlas of Heart Disease and Stroke offers a way to visualize, export, and generate reports from heart disease and stroke mortality data, as well as data regarding...

-   Prevalence
-   Risk Factors
-   Social, Economic, Environmental variables
-   Demographics
-   Health Care Delivery and Insurance
-   Health Care Costs

{{< pagebreak >}}

## Environmental Justice Index (EJI)

+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**         | A list of all the measures of environmental justice in the United States. This helps communities find and fix environmental injustices, with a focus on vulnerable groups that are gripped by health risks in the environment. |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Time Frame**          | Year; 2023                                                                                                                                                                                                                     |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Spatial Scale**       | National, state, and local (county or census tract) levels                                                                                                                                                                     |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Format**              | Tables and Shapefiles                                                                                                                                                                                                          |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Source**              | Centers of Disease Control and Prevention (CDC)                                                                                                                                                                                |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Original Repository** | [2022](https://www.atsdr.cdc.gov/placeandhealth/eji/eji-data-download.html)                                                                                                                                                    |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Living Atlas**        | N/A                                                                                                                                                                                                                            |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

|                             |
|-----------------------------|
| {tbl-colwidths="\[20,80\]"} |

**Details**\
This EJI dataset contains variables such as air and water quality, exposure to hazardous waste, and socioeconomic status. It is used to develop and implement policies, and advocate for better environmental health equality. The research presents data at the city and census tract levels, obtaining metrics of environmental justice using small area estimation techniques. These estimates indicate developing health issues and support the establishment of focused public health preventative measures. 

{{< pagebreak >}}

## Federally Qualified Health Center Service Delivery and Look-Alike Sites

+-------------------------+-----------------------------------------------------------------------+
| **Description**         | List of federally-funded health centers that provide health services. |
+-------------------------+-----------------------------------------------------------------------+
| **Time Frame**          | Updated on Unknown Basis; Current                                     |
+-------------------------+-----------------------------------------------------------------------+
| **Spatial Scale**       | Point                                                                 |
+-------------------------+-----------------------------------------------------------------------+
| **Format**              | CSV with Address and X/Y                                              |
+-------------------------+-----------------------------------------------------------------------+
| **Source**              | Health Resources & Services Administration (HRSA)                     |
+-------------------------+-----------------------------------------------------------------------+
| **Original Repository** | [Current](https://data.hrsa.gov/data/download)                        |
+-------------------------+-----------------------------------------------------------------------+
| **Living Atlas**        | N/A                                                                   |
+-------------------------+-----------------------------------------------------------------------+

: {tbl-colwidths="\[20,80\]"}

**Details**\
Health centers are community-based and consumer-run organizations that serve populations with limited access to health care. These include low-income populations, the uninsured, those with limited English proficiency, migratory and seasonal agricultural workers, individuals and families experiencing homelessness, and those living in public housing.

{{< pagebreak >}}

## Healthcare Facilities of the Indian Health Service (IHS)

+-------------------------+--------------------------------------------------------------------------------------+
| **Description**         | Point-level representation of the locations of IHS Facilities in the United States   |
+-------------------------+--------------------------------------------------------------------------------------+
| **Time Frame**          | Updated on Unknown Basis; Currents                                                   |
+-------------------------+--------------------------------------------------------------------------------------+
| **Spatial Scale**       | Point                                                                                |
+-------------------------+--------------------------------------------------------------------------------------+
| **Format**              | Feature Service                                                                      |
+-------------------------+--------------------------------------------------------------------------------------+
| **Source**              | Indian Health Service (IHS)                                                          |
+-------------------------+--------------------------------------------------------------------------------------+
| **Original Repository** | [Current](https://www.ihs.gov/locations/)                                            |
+-------------------------+--------------------------------------------------------------------------------------+
| **Living Atlas**        | [Current](https://www.arcgis.com/home/item.html?id=f54bca11a622446c9472e962fdaf2bea) |
+-------------------------+--------------------------------------------------------------------------------------+

: {tbl-colwidths="\[20,80\]"}

**Details**\
The IHS is an agency within the Department of Health and Human Services responsible for providing federal health services to American Indians and Alaska Natives. These services include hospitals, behavioral health facilities, health centers, dental clinics, health stations, Alaska Village Clinics and other services. The IHS is the principal federal health care provider and health advocate for Indian people, and its goal is to raise their health status to the highest possible level. The IHS provides a comprehensive health service delivery system for American Indians and Alaska Natives who are members of 566 federally recognized Tribes across the U.S.

{{< pagebreak >}}

## Hospitals \| HIFLD

+-------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**         | Locations and characteristics of hospitals located all throughout the United States and its territories are included in the Hospitals dataset that is part of the Homeland Infrastructure Foundation-Level Data (HIFLD) database. In addition to supporting research, it is used to improve community preparation and resiliency. |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Time Frame**          | Year; 2020 to 2024                                                                                                                                                                                                                                                                                                                |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Spatial Scale**       | National level, including all 50 U.S. states, Washington D.C., and U.S. territories such as Puerto Rico, Guam, American Samoa, Northern Mariana Islands, Palau, and the Virgin Islands.                                                                                                                                           |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Format**              | CSV, KML, Shapefiles, and other GIS-compatible formats                                                                                                                                                                                                                                                                            |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Source**              | State Department of Health, federal organizations like the Department of Health and Human Services (HHS), and other credible sources.                                                                                                                                                                                             |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Original Repository** | [2020 to 2024](https://hifld-geoplatform.hub.arcgis.com/datasets/geoplatform::hospitals/explore?location=0.009275%2C-15.457895%2C0.00&showTable=true)                                                                                                                                                                             |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Living Atlas**        | N/A                                                                                                                                                                                                                                                                                                                               |
+-------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

{tbl-colwidths="\[20,80\]"}

**Details**\
Some of the hospitals that are included in the dataset include general acute care hospitals, critical access hospitals, military hospitals, mental hospitals, rehabilitation hospitals, children hospitals, and further hospitals. This project comprises several characteristics such as the name of the hospital, its location, its kind, its capacity, and the availability of emergency services. This comprehensive dataset provides assistance for planning and response actions at the federal, state, and local levels, ensuring that critical information is accessible for initiatives pertaining to public health and safety.

{{< pagebreak >}}

## Mapping Medicare Disparities

+-------------------------+------------------------------------------------------------------------------------------------+
| **Description**         | Health outcomes measures to map Medicare disparities                                           |
+-------------------------+------------------------------------------------------------------------------------------------+
| **Time Frame**          | Updated on Unknown Basis; Current                                                              |
+-------------------------+------------------------------------------------------------------------------------------------+
| **Spatial Scale**       | State/Territory, County, Tract (depending on measure)                                          |
+-------------------------+------------------------------------------------------------------------------------------------+
| **Format**              | CSV                                                                                            |
+-------------------------+------------------------------------------------------------------------------------------------+
| **Source**              | Center of Medicare & Medicaid Services                                                         |
+-------------------------+------------------------------------------------------------------------------------------------+
| **Original Repository** | [Current](https://data.cms.gov/tools/mapping-medicare-disparities-by-population) (date listed) |
+-------------------------+------------------------------------------------------------------------------------------------+
| **Living Atlas**        | N/A                                                                                            |
+-------------------------+------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[20,80\]"}

**Details**\
Composed of multiple tools which display disparities through three views:

-   Population - "The MMD interactive tool contains health outcome measures for disease prevalence, costs, hospitalization for 60 specific chronic conditions, emergency department utilization, readmissions rates, mortality, preventable hospitalizations, and preventive services."
-   Hospital - "The MMD interactive map hospital tool identifies area of disparities between hospital quality and cost of care. It allows for a way to compare measures at the hospital, county, state, territory, and national levels"
-   Social Determinants of Health - "This addition to the MMD tool identifies areas of disparities by key Social Determinant of Health (SDOH) domains and measures"

{{< pagebreak >}}

## Multidimensional Deprivation Index (MDI)

+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**         | Measure of an area’s social determinants of health status, or “deprivation,” based on the American Community Survey                                                          |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Time Frame**          | Mixed; 2010 to 2019; 2017                                                                                                                                                    |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Spatial Scale**       | County and State                                                                                                                                                             |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Format**              | Shapefile                                                                                                                                                                    |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Source**              | US Census Bureau                                                                                                                                                             |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Original Repository** | [2010 to 2019](https://www.census.gov/topics/income-poverty/poverty/about/related-sites/rates.html) [2017](https://www.census.gov/library/publications/2019/acs/acs-40.html) |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Living Atlas**        | N/A                                                                                                                                                                          |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[20,80\]"}

**Details**\
MDI value is equal to the percent of households in that region that qualify as “deprived.” Can be treated as an exposure value. A composite measure based on six dimensions:

-   Neighborhood Quality
-   Standard of Living
-   Education
-   Health
-   Economic Security
-   Housing Quality

Cannot map by individual dimension.

{{< pagebreak >}}

## Population Level Analysis and Community Estimates (PLACES)

+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**         | The PLACES Project replaces the 500 Cities Project and provides model-based population-level analysis and community estimates for the entire US at several spatial scales |
+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Time Frame**          | Year; 2019 to 2023                                                                                                                                                        |
+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Spatial Scale**       | Counties, Places, ZCTAs, and Census Tracts                                                                                                                                |
+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Format**              | Tables and Shapefiles                                                                                                                                                     |
+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Source**              | Centers for Disease Control and Prevention (CDC)                                                                                                                          |
+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Original Repository** | [All Years](https://data.cdc.gov/browse?category=500+Cities+%26+Places)                                                                                                   |
+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Living Atlas**        | [Current](https://www.arcgis.com/home/item.html?id=3b7221d4e47740cab9235b839fa55cd7)                                                                                      |
+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[20,80\]"}

**Details**\
This project reported city- and census tract-level data and used small area estimation methods to obtain 29 chronic disease measures for the United States.

Dataset includes estimates for 29 measures (definitions here):

-   Chronic Disease Related Health Outcomes (13)
-   Prevention Measures (9)
-   Health Risk Behaviors (4)
-   Disability (7)
-   Health Status (3)

These estimates can be used to identify emerging health problems and to inform development and implementation of effective, targeted public health prevention activities. Because the small area model cannot detect effects due to local interventions, users are cautioned against using these estimates for program or policy evaluations.

{{< pagebreak >}}

## Rural-Urban Commuting Area (RUCA)

+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**         | The rural-urban commuting area (RUCA) codes classify U.S. census tracts using measures of population density, urbanization, and daily commuting. Also approximated at ZIP code level |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Time Frame**          | Mixed; 1990, 2000, and 2010 Decennial Census, 2006-10 ACS                                                                                                                            |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Spatial Scale**       | County level representation of counties that are defined as PRCDAs/CHSDA                                                                                                             |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Format**              | CSV with GEOIDs                                                                                                                                                                      |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Source**              | US Department of Agriculture Economic Research Service                                                                                                                               |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Original Repository** | [All Years](https://www.ers.usda.gov/data-products/rural-urban-commuting-area-codes/)                                                                                                |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Living Atlas**        | N/A                                                                                                                                                                                  |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[20,80\]"}

**Details**\
The classification contains two levels. Whole numbers (1-10) delineate metropolitan, micropolitan, small town, and rural commuting areas based on the size and direction of the primary (largest) commuting flows. These 10 codes are further subdivided based on secondary commuting flows, providing flexibility in combining levels to meet varying definitional needs and preferences.

{{< pagebreak >}}

## Shortage Areas (HPSAs and MUA/Ps)

+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**         | Facility, population, and geographic boundaries for Health Professional Shortage Areas (HPSAs) and Medically Underserved Areas/Populations (MUA/Ps). |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Time Frame**          | Updated on Unknown Basis; Current                                                                                                                    |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Spatial Scale**       | Mixed (Point, Tract, County Subdivision, County)                                                                                                     |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Format**              | Shapefile and Feature Service                                                                                                                        |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Source**              | Health Resources & Services Administration                                                                                                           |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Original Repository** | [Current](https://data.hrsa.gov/data/download#heading12)                                                                                             |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Living Atlas**        | N/A                                                                                                                                                  |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[20,80\]"}

**Details**\
HRSA’s Bureau of Health Workforce (BHW) develops shortage designation criteria and uses them to decide whether or not a geographic area or population group is a Health Professional Shortage Area (HPSA), Medically Underserved Area (MUA), or Medically Underserved Population (MUP). For HPSAs, scores range from 1 to 25 for primary care and mental health, 1 to 26 for dental health. The higher the score, the greater the priority. HPSAs may have shortages of primary medical care, dental, or mental health providers; may be urban or rural areas; population groups; or medical or other public facilities.

{{< pagebreak >}}

## Small Area Health Insurance Estimate (SAHIE) Program

+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**         | Offers estimates of health insurance coverage in countries and states throughout the United States. It aids in the identification of locations with large uninsured populations, as well as policy-making and resource allocation. |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Time Frame**          | Mixed; 2000, 2001, 2005 to 2007, 2008 to 2021                                                                                                                                                                                      |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Spatial Scale**       | County and state level across the United States                                                                                                                                                                                    |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Format**              | CSV and Shapefile                                                                                                                                                                                                                  |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Source**              | U.S. Census Bureau                                                                                                                                                                                                                 |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Original Repository** | [All Years](https://www.census.gov/programs-surveys/sahie/data/datasets.html)                                                                                                                                                      |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Living Atlas**        |                                                                                                                                                                                                                                    |
+-------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

{tbl-colwidths="\[20,80\]"}

**Details**\
This project presents statistics at the county and state levels about health insurance coverage in the United States. Estimates for several demographic groups are included in the dataset, which is arranged by: 

-   Age Groups

-   Levels of income

-   Race and ethnicity (in states)

-   Gender

These estimates aid in identifying regions with a significant number of individuals without health insurance coverage and provide valuable information for implementing focused initiatives to reach out and enroll them in health insurance programs.

{{< pagebreak >}}

## Small Area Income and Poverty Estimates (SAIPE) Program

+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**         | Offers yearly estimates of income and poverty information for every school district, country and state in the United States. The primary goal is to facilitate the management of federal programs and distribution of federal funding to local authorities. |
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Time Frame**          | Year; 1989 to 2022                                                                                                                                                                                                                                          |
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Spatial Scale**       | County, state, and school district levels across the United States                                                                                                                                                                                          |
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Format**              | Tables                                                                                                                                                                                                                                                      |
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Source**              | U.S. Census Bureau                                                                                                                                                                                                                                          |
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Original Repository** | [All Years](https://www.census.gov/programs-surveys/saipe/data/datasets.All.List_1743592724.html#list-tab-List_1743592724)                                                                                                                                  |
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Living Atlas**        |                                                                                                                                                                                                                                                             |
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

**Details**\
This research presents yearly estimates of income and poverty data, encompassing: 

-   Total number of people in poverty

-   Number of children under age 18 in poverty

-   Number of related children ages 5 to 17 in families in poverty 

-   Median household income

Produced for every school district, county, and state, these figures help pinpoint locations with high poverty rates, which in turn informs policy choices and the creation of targeted solutions. 

{{< pagebreak >}}

## Social Vulnerability Index (SVI)

+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**         | The [Social Vulnerability Index](https://www.atsdr.cdc.gov/placeandhealth/svi/index.html) uses 15 U.S. census variables to help local officials identify communities that may need support before, during, or after disasters. |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Time Frame**          | Year; 2000, 2010, 2014, 2016, 2018, 2020                                                                                                                                                                                       |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Spatial Scale**       | County and Census Tract                                                                                                                                                                                                        |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Format**              | CSV and Shapefile                                                                                                                                                                                                              |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Source**              | Centers for Disease Control and Prevention (CDC)                                                                                                                                                                               |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Original Repository** | [All Years](https://www.atsdr.cdc.gov/placeandhealth/svi/data_documentation_download.html)                                                                                                                                     |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Living Atlas**        | [2018](https://www.arcgis.com/home/item.html?id=cbd68d9887574a10bc89ea4efe2b8087) [2020](https://www.arcgis.com/home/item.html?id=05709059044243ae9b42f469f0e06642)                                                            |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[20,80\]"}

**Details**\
Ranking by social vulnerability. Can look at rank within a state or within the entire US. A composite measure based on four dimensions:

-   Housing Type and Transportation
-   Household Composition and Disability
-   Socioeconomic Status
-   Minority Status and Language

Can also map by individual dimension.

{{< pagebreak >}}

## Tribal Census Tract Boundaries

+-------------------------+------------------------------------------------------------------------------------+
| **Description**         | Polygons representing individual tribal census tracts throughout the United States |
+-------------------------+------------------------------------------------------------------------------------+
| **Years**               | Year; 2007 to 2023                                                                 |
+-------------------------+------------------------------------------------------------------------------------+
| **Spatial Scale**       | Tribal Tract                                                                       |
+-------------------------+------------------------------------------------------------------------------------+
| **Format**              | Shapefile                                                                          |
+-------------------------+------------------------------------------------------------------------------------+
| **Source**              | US Census Bureau                                                                   |
+-------------------------+------------------------------------------------------------------------------------+
| **Original Repository** | [All Years](https://www.census.gov/cgi-bin/geo/shapefiles/index.php)               |
+-------------------------+------------------------------------------------------------------------------------+
| **Living Atlas**        | N/A                                                                                |
+-------------------------+------------------------------------------------------------------------------------+

: {tbl-colwidths="\[20,80\]"}

**Details:**\
Tribal census tracts are small statistical subdivisions of a reservation and off- reservation trust land. Their primary purpose is the same as census tracts: the presentation of statistical data. However, rather than nesting within a county, tribal census tracts nest within a single federally recognized American Indian area, providing coverage across all federally recognized American Indian reservations and off-reservation trust lands. Tribal census tracts have population criteria identical to county-based census tracts.

If you would like attributes associated with these Tribal Census Tract Boundaries, you can visit <https://data2.nhgis.org/main.> Select **Geographic levels -\> Native American/Alaskan/Hawaiian -\> Tribal Census Tracts**. You can then select years, topics, and datasets to filter ACS Tables
