## 500 Cities

|                         |                                                                                                                                                                                                                                                                                                                                                                                     |
|------------|------------------------------------------------------------|
| **Description**         | The [500 Cities Project](https://www.cdc.gov/places/about/500-cities-2016-2019/index.html) provided model derived estimates for chronic disease risk factors, health outcomes, and clinical preventive services use for the 500 largest US cities.                                                                                                                                  |
| **Time Frame**          | Year; 2016 to 2019                                                                                                                                                                                                                                                                                                                                                                  |
| **Spatial Scale**       | City and Census Tract                                                                                                                                                                                                                                                                                                                                                               |
| **Format**              | Tables and Shapefiles                                                                                                                                                                                                                                                                                                                                                               |
| **Source**              | Centers for Disease Control and Prevention (CDC)                                                                                                                                                                                                                                                                                                                                    |
| **Original Repository** | [All Years](https://data.cdc.gov/browse?q=GIS%20friendly&sortBy=relevance) (Look for datasets labeled GIS Friendly Format)                                                                                                                                                                                                                                                          |
| **Living Atlas**        | [2016](https://cdcarcgis.maps.arcgis.com/home/item.html?id=ea8b721cf9034814bce067ddefd21ecc) [2017](https://cdcarcgis.maps.arcgis.com/home/item.html?id=2064702cb1fe47e5868333f56d4c99d0) [2018](https://cdcarcgis.maps.arcgis.com/home/item.html?id=04bd589e13c242d98de43e78f90d0d3f) [2019](https://cdcarcgis.maps.arcgis.com/home/item.html?id=7f48652a35424b97b2bc2542c4ef26ae) |

: {tbl-colwidths="\[20,80\]"}

**Details**\
This project reported city- and census tract-level data and used small area estimation methods to obtain 27 chronic disease measures for the 500 largest American cities. Dataset includes estimates for 27 measures ([definitions here](https://www.cdc.gov/places/measure-definitions/index.html)):

-   Chronic disease-related unhealthy behaviors (5),
-   Health outcomes (13), and
-   Use of preventive services (9).

These estimates can be used to identify emerging health problems and to inform development and implementation of effective, targeted public health prevention activities. Because the small area model cannot detect effects due to local interventions, users are cautioned against using these estimates for program or policy evaluations.