## Division for Heart Disease and Stroke Prevention - Heart Disease and Stroke Mortality

+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**         | Heart Disease and Stoke Mortality                                                                                                                                                                                                                                                                                                                                              |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Time Frame**          | Three year average from 2005-2007 to 2019-2021                                                                                                                                                                                                                                                                                                                                 |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Spatial Scale**       | States, Counties                                                                                                                                                                                                                                                                                                                                                               |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Format**              | Tables                                                                                                                                                                                                                                                                                                                                                                         |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Source**              | Centers for Disease Control and Prevention (CDC) Division for Heart Disease and Stroke Prevention                                                                                                                                                                                                                                                                              |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Original Repository** | [Interactive Data Atlas](https://nccd.cdc.gov/DHDSPAtlas/Default.aspx)                                                                                                                                                                                                                                                                                                         |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Living Atlas**        | Heart Disease Mortality - [2014-2016](https://www.arcgis.com/home/item.html?id=d8b5477dad474e2d85cae6b8c069003e) [2017-2019](https://www.arcgis.com/home/item.html?id=ad21224485f049ee85808504c406c9ed) [2018-2020](https://www.arcgis.com/home/item.html?id=3d67302da1cf4b0d820b613c7949e958)                                                                                 |
|                         |                                                                                                                                                                                                                                                                                                                                                                                |
|                         | Stroke Mortality - [2014-2016](https://www.arcgis.com/home/item.html?id=21501f65faf84279afb41f040e82b4af) [2016-2018](https://www.arcgis.com/home/item.html?id=713d4cd763e24507b2b7688b96ab9416) [2017-2019](https://www.arcgis.com/home/item.html?id=417107aaaf7b471d918db5b2bafe9c9e) [2018-2020](https://www.arcgis.com/home/item.html?id=60a486432fcc4b70bcc5b9adf6155242) |
+-------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[20,80\]"}

**Details**\
Offers Heart Disease and Stroke mortality data obtained from the National Vital Statistics System. Data can be stratified by age, race/ethnicity, and gender. The Interactive Atlas of Heart Disease and Stroke offers a way to visualize, export, and generate reports from heart disease and stroke mortality data, as well as data regarding...

-   Prevalence
-   Risk Factors
-   Social, Economic, Environmental variables
-   Demographics
-   Health Care Delivery and Insurance
-   Health Care Costs