## American Community Survey (ACS) 5-year Estimates

|                         |                                                                                                                                                                                                                                                                                                                                                                              |
|------------|------------------------------------------------------------|
| **Description**         | "The [American Community Survey](https://www.census.gov/programs-surveys/acs/about.html) (ACS) is an ongoing survey that provides vital information on a yearly basis about our nation and its people. Information from the survey generates data that help determine how more than \$675 billion in federal and state funds are distributed each year.” (U.S Census Bureau) |
| **Time Frame**          | 5 Years; 2009 to 2022                                                                                                                                                                                                                                                                                                                                                        |
| **Spatial Scale**       | Nation, State (including DC and Puerto Rico), Metropolitan Area, Congressional District, County, Place, Census Tract and Block Group                                                                                                                                                                                                                                         |
| **Format**              | Feature Layers                                                                                                                                                                                                                                                                                                                                                               |
| **Source**              | US Census Bureau                                                                                                                                                                                                                                                                                                                                                             |
| **Original Repository** | [All Years](https://data.census.gov/)                                                                                                                                                                                                                                                                                                                                        |
| **Living Atlas**        | [Current](https://www.arcgis.com/home/group.html?id=16b3a5ac36834ed6b3f16261d9a988ea#overview)                                                                                                                                                                                                                                                                               |

: {tbl-colwidths="\[20,80\]"}

**Details**\
The Living Atlas hosts the current ACS 5-year estimates in a series of several features grouped by topic. Each topic is hosted as both [boundaries and centroids](https://storymaps.arcgis.com/stories/41743d0d5364488fb51d795d65b40b37). Topics may contain single or multiple ACS tables Layers can be [accessed and used](https://www.arcgis.com/apps/Cascade/index.html?appid=c6a35a434a8f4913b9c35022290efdd0) within your GIS workflows, for example, [make a map about your community](https://www.esri.com/arcgis-blog/products/arcgis-living-atlas/mapping/make-an-acs-map-fast/).

If you are looking for historical data, the census.gov website can be difficult to go through. [Census Reporter](https://censusreporter.org/) can make it easier to find and download tables at various spatial scales.