## NebraskaMap

|  |  |
|--------------------|----------------------------------------------------|
| **Description** | The NebrasksaMap maintains a comprehensive database of geospatial data. Data within the portal covers subjects such as administrative boundaries, climate, health, infrastructure, and transportation. |
| **Time Frame** | Varies |
| **Spatial Scale** | Varies |
| **Format** | Varies |
| **Source** | Nebraska Geographic Information Office |
| **Original Repository** | [Data Portal](https://www.nebraskamap.gov/) |
| **Living Atlas** | N/A |

: {tbl-colwidths="\[20,80\]"}

**Details**\
The NebraskaMap includes many healthcare infrastructure datasets like:

-   [DHHS Rural Health Clinics](https://www.nebraskamap.gov/datasets/nebraska::dhhs-rural-health-clinics/about)

-   [DHHS Hospitals](https://www.nebraskamap.gov/datasets/nebraska::dhhs-hospitals/about)

-   [DHHS Assisted Living Facilities](https://www.nebraskamap.gov/datasets/nebraska::dhhs-assisted-living-facilities/about)

-   [DHHS Long Term Care Facilities](https://www.nebraskamap.gov/datasets/nebraska::dhhs-long-term-care-facilities/about)

All datasets can be easily imported into ArcGIS Pro by clicking Download -\> Data Source; Access. Copy the website URL and within ArcGIS Pro click on Add Data -\> From Path and paste the URL.