## Environmental Justice Index (EJI)

|  |  |
|--------------------|----------------------------------------------------|
| **Description** | A list of all the measures of environmental justice in the United States. This helps communities find and fix environmental injustices, with a focus on vulnerable groups that are gripped by health risks in the environment. |
| **Time Frame** | Year; 2022 & 2024 |
| **Spatial Scale** | Nation, State, County, and Census Tract |
| **Format** | CSV and Geodatabase |
| **Source** | Centers of Disease Control and Prevention (CDC) |
| **Original Repository** | [All years](https://www.atsdr.cdc.gov/place-health/php/eji/eji-data-download.html) |
| **Living Atlas** | N/A |

: {tbl-colwidths="\[20,80\]"}

**Details**\
The EJI is an aggregate measure of environmental burden that incorporates data from the Census Bureau, Environmenatal Protection Agency, Mine Safety and Health Administation and Centers of Disease Control and Prevention. The index measure is broken down into the modules: Environmental Burden, Social Vulnerability, and Health Vulnerability which are formed by 36 environmental, social, and health factors. The Environmental Burden and Social Vulnerability burden modules also form the Social-Environmental Ranking (SER), which aims to measure distributive and procedural environmental justice factors.