## Division for Heart Disease and Stroke Prevention - Heart Disease and Stroke Mortality

|                         |                                                                                                                                                        |
|------------|------------------------------------------------------------|
| **Description**         | Heart Disease and Stoke Mortality                                                                                                                      |
| **Time Frame**          | Three year average from 2005-2007 to 2019-2021                                                                                                         |
| **Spatial Scale**       | States, Counties                                                                                                                                       |
| **Format**              | Tables                                                                                                                                                 |
| **Source**              | Centers for Disease Control and Prevention (CDC) Division for Heart Disease and Stroke Prevention                                                      |
| **Original Repository** | [Interactive Data Atlas](https://nccd.cdc.gov/DHDSPAtlas/Default.aspx)                                                                                 |
| **Living Atlas**        | [All Years](https://www.arcgis.com/home/search.html?restrict=false&sortField=relevance&sortOrder=desc&searchTerm=owner%3A%22data_cdc_dhdsp%22#content) |

: {tbl-colwidths="\[20,80\]"}

**Details**\
Offers Heart Disease and Stroke mortality data obtained from the National Vital Statistics System. Data can be stratified by age, race/ethnicity, and gender. The Interactive Atlas of Heart Disease and Stroke offers a way to visualize, export, and generate reports from heart disease and stroke mortality data, as well as data regarding...

-   Prevalence
-   Risk Factors
-   Social, Economic, Environmental variables
-   Demographics
-   Health Care Delivery and Insurance
-   Health Care Costs